

default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: tp_app_development

test:
  <<: *default
  database: tp_app_test

production:
  <<: *default
  database: tp_app_production
  username: tp_app
  password: <%= ENV['TP_APP_DATABASE_PASSWORD'] %>
